name: Deploy to Skynet
on:
  pull_request:
jobs:
  build:
  runs-on: ubuntu-latest
steps:
  — uses: actions/checkout@v2
  — name: Deploy to Skynet
    uses: kwypchlo/deploy-to-skynet-action@main
    with:
      upload-dir: public
      github-token: ${{ secrets.GITHUB_TOKEN }}
